title: Lingli Wang's Homepage
page-top-title: Lingli Wang
top-section-bg-text: Data Science and Big Data Technology
home-subtitle: Lingli Wang&esfj|王苓郦
copyright-text: '&copy; Lingli Wang 2023-2024. All Rights Reserved.'
